from __future__ import annotations

from enum import StrEnum


class ErrorCode(StrEnum):
    REQUEST_ID_CONFLICT = "REQUEST_ID_CONFLICT"
    DEVICE_NOT_FOUND = "DEVICE_NOT_FOUND"
    DEVICE_READONLY = "DEVICE_READONLY"
    DEVICE_OFFLINE = "DEVICE_OFFLINE"
    INVALID_CONTROL_PAYLOAD = "INVALID_CONTROL_PAYLOAD"
    PIN_SESSION_REQUIRED = "PIN_SESSION_REQUIRED"
