from __future__ import annotations

from enum import StrEnum


class ErrorCode(StrEnum):
    INVALID_PARAMS = "INVALID_PARAMS"
    UNAUTHORIZED = "UNAUTHORIZED"
    NOT_FOUND = "NOT_FOUND"
    METHOD_NOT_ALLOWED = "METHOD_NOT_ALLOWED"
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
    REQUEST_ID_CONFLICT = "REQUEST_ID_CONFLICT"
    VERSION_CONFLICT = "VERSION_CONFLICT"
    DEVICE_NOT_FOUND = "DEVICE_NOT_FOUND"
    CONTROL_REQUEST_NOT_FOUND = "CONTROL_REQUEST_NOT_FOUND"
    READONLY_DEVICE = "READONLY_DEVICE"
    DEVICE_OFFLINE = "DEVICE_OFFLINE"
    HA_UNAVAILABLE = "HA_UNAVAILABLE"
    PIN_REQUIRED = "PIN_REQUIRED"
    PIN_LOCKED = "PIN_LOCKED"
    DRAFT_LOCK_LOST = "DRAFT_LOCK_LOST"
    DRAFT_LOCK_TAKEN_OVER = "DRAFT_LOCK_TAKEN_OVER"
    UNSUPPORTED_ACTION = "UNSUPPORTED_ACTION"
    UNSUPPORTED_TARGET = "UNSUPPORTED_TARGET"
    VALUE_OUT_OF_RANGE = "VALUE_OUT_OF_RANGE"
