/* This file was auto-generated by json-schema-to-typescript. Do not make direct changes. */

export type ClientMessage = RealtimeAckMessage | RealtimeResumeMessage | RealtimePollMessage;
export type EventId = string;
export type Type = "ack";
export type LastEventId = string | null;
export type Type1 = "resume";
export type Type2 = "poll";
export type ServerEvent =
  | SettingsUpdatedEvent
  | SummaryUpdatedEvent
  | DeviceStateChangedEvent
  | MediaStateChangedEvent
  | HaSyncRecoveredEvent
  | HaSyncDegradedEvent
  | EnergyRefreshCompletedEvent
  | EnergyRefreshFailedEvent
  | DraftLockAcquiredEvent
  | PublishSucceededEvent
  | BackupRestoreCompletedEvent
  | VersionConflictDetectedEvent;
export type ChangeDomain = "SETTINGS";
export type EventId1 = string;
export type EventType = "settings_updated";
export type HomeId = string;
export type OccurredAt = string;
export type EffectiveAt = string;
export type SettingsVersion = string;
export type UpdatedDomains = string[];
export type Sequence = number;
export type SnapshotRequired = true;
export type ChangeDomain1 = "SUMMARY";
export type EventId2 = string;
export type EventType1 = "summary_updated";
export type HomeId1 = string;
export type OccurredAt1 = string;
export type DeviceCount = number;
export type EntityCount = number;
export type LinkedEntityCount = number;
export type RoomCount = number;
export type Sequence1 = number;
export type SnapshotRequired1 = false;
export type ChangeDomain2 = "DEVICE_STATE";
export type EventId3 = string;
export type EventType2 = "device_state_changed";
export type HomeId2 = string;
export type OccurredAt2 = string;
export type ConfirmationType = string | null;
export type DeviceId = string;
export type EntityId = string | null;
export type ErrorCode = string | null;
export type ErrorMessage = string | null;
export type ExecutionStatus = string | null;
export type HomeId3 = string | null;
export type RelatedRequestId = string | null;
export type RuntimeState = {
  [k: string]: unknown;
} | null;
export type Status = string | null;
export type Sequence2 = number;
export type SnapshotRequired2 = false;
export type ChangeDomain3 = "DEVICE_STATE";
export type EventId4 = string;
export type EventType3 = "media_state_changed";
export type HomeId4 = string;
export type OccurredAt3 = string;
export type Sequence3 = number;
export type SnapshotRequired3 = false;
export type ChangeDomain4 = "SUMMARY";
export type EventId5 = string;
export type EventType4 = "ha_sync_recovered";
export type HomeId5 = string;
export type OccurredAt4 = string;
export type ConnectionStatus = string;
export type HomeId6 = string;
export type Message = string;
export type Sequence4 = number;
export type SnapshotRequired4 = false;
export type ChangeDomain5 = "SUMMARY";
export type EventId6 = string;
export type EventType5 = "ha_sync_degraded";
export type HomeId7 = string;
export type OccurredAt5 = string;
export type Sequence5 = number;
export type SnapshotRequired5 = false;
export type ChangeDomain6 = "ENERGY";
export type EventId7 = string;
export type EventType6 = "energy_refresh_completed";
export type HomeId8 = string;
export type OccurredAt6 = string;
export type RefreshStatus = string;
export type Sequence6 = number;
export type SnapshotRequired6 = false;
export type ChangeDomain7 = "ENERGY";
export type EventId8 = string;
export type EventType7 = "energy_refresh_failed";
export type HomeId9 = string;
export type OccurredAt7 = string;
export type Sequence7 = number;
export type SnapshotRequired7 = false;
export type ChangeDomain8 = "EDITOR_LOCK";
export type EventId9 = string;
export type EventType8 = "draft_lock_acquired";
export type HomeId10 = string;
export type OccurredAt8 = string;
export type LeaseExpiresAt = string;
export type LeaseId = string;
export type TerminalId = string;
export type Sequence8 = number;
export type SnapshotRequired8 = false;
export type ChangeDomain9 = "LAYOUT";
export type EventId10 = string;
export type EventType9 = "publish_succeeded";
export type HomeId11 = string;
export type OccurredAt9 = string;
export type EffectiveAt1 = string;
export type LayoutVersion = string;
export type PublishedByTerminalId = string;
export type Sequence9 = number;
export type SnapshotRequired9 = true;
export type ChangeDomain10 = "BACKUP";
export type EventId11 = string;
export type EventType10 = "backup_restore_completed";
export type HomeId12 = string;
export type OccurredAt10 = string;
export type BackupId = string;
export type EffectiveAt2 = string;
export type LayoutVersion1 = string;
export type RestoredByTerminalId = string;
export type SettingsVersion1 = string;
export type Sequence10 = number;
export type SnapshotRequired10 = true;
export type ChangeDomain11 = "SUMMARY";
export type EventId12 = string;
export type EventType11 = "version_conflict_detected";
export type HomeId13 = string;
export type OccurredAt11 = string;
export type LastEventId1 = string;
export type Reason = "EVENT_GAP";
export type Sequence11 = number;
export type SnapshotRequired11 = true;

export interface RealtimeContractBundle {
  client_message: ClientMessage;
  server_event: ServerEvent;
}
export interface RealtimeAckMessage {
  event_id: EventId;
  type: Type;
}
export interface RealtimeResumeMessage {
  last_event_id?: LastEventId;
  type: Type1;
}
export interface RealtimePollMessage {
  type: Type2;
}
export interface SettingsUpdatedEvent {
  change_domain: ChangeDomain;
  event_id: EventId1;
  event_type: EventType;
  home_id: HomeId;
  occurred_at: OccurredAt;
  payload: SettingsUpdatedPayload;
  sequence: Sequence;
  snapshot_required: SnapshotRequired;
}
export interface SettingsUpdatedPayload {
  effective_at: EffectiveAt;
  settings_version: SettingsVersion;
  updated_domains: UpdatedDomains;
}
export interface SummaryUpdatedEvent {
  change_domain: ChangeDomain1;
  event_id: EventId2;
  event_type: EventType1;
  home_id: HomeId1;
  occurred_at: OccurredAt1;
  payload: SummaryUpdatedPayload;
  sequence: Sequence1;
  snapshot_required: SnapshotRequired1;
}
export interface SummaryUpdatedPayload {
  device_count: DeviceCount;
  entity_count: EntityCount;
  linked_entity_count: LinkedEntityCount;
  room_count: RoomCount;
}
export interface DeviceStateChangedEvent {
  change_domain: ChangeDomain2;
  event_id: EventId3;
  event_type: EventType2;
  home_id: HomeId2;
  occurred_at: OccurredAt2;
  payload: DeviceStateChangedPayload;
  sequence: Sequence2;
  snapshot_required: SnapshotRequired2;
}
export interface DeviceStateChangedPayload {
  confirmation_type?: ConfirmationType;
  device_id: DeviceId;
  entity_id?: EntityId;
  error_code?: ErrorCode;
  error_message?: ErrorMessage;
  execution_status?: ExecutionStatus;
  home_id?: HomeId3;
  related_request_id?: RelatedRequestId;
  runtime_state?: RuntimeState;
  status?: Status;
}
export interface MediaStateChangedEvent {
  change_domain: ChangeDomain3;
  event_id: EventId4;
  event_type: EventType3;
  home_id: HomeId4;
  occurred_at: OccurredAt3;
  payload: DeviceStateChangedPayload;
  sequence: Sequence3;
  snapshot_required: SnapshotRequired3;
}
export interface HaSyncRecoveredEvent {
  change_domain: ChangeDomain4;
  event_id: EventId5;
  event_type: EventType4;
  home_id: HomeId5;
  occurred_at: OccurredAt4;
  payload: ConnectionStatusPayload;
  sequence: Sequence4;
  snapshot_required: SnapshotRequired4;
}
export interface ConnectionStatusPayload {
  connection_status: ConnectionStatus;
  home_id: HomeId6;
  message: Message;
}
export interface HaSyncDegradedEvent {
  change_domain: ChangeDomain5;
  event_id: EventId6;
  event_type: EventType5;
  home_id: HomeId7;
  occurred_at: OccurredAt5;
  payload: ConnectionStatusPayload;
  sequence: Sequence5;
  snapshot_required: SnapshotRequired5;
}
export interface EnergyRefreshCompletedEvent {
  change_domain: ChangeDomain6;
  event_id: EventId7;
  event_type: EventType6;
  home_id: HomeId8;
  occurred_at: OccurredAt6;
  payload: EnergyRefreshPayload;
  sequence: Sequence6;
  snapshot_required: SnapshotRequired6;
}
export interface EnergyRefreshPayload {
  refresh_status: RefreshStatus;
}
export interface EnergyRefreshFailedEvent {
  change_domain: ChangeDomain7;
  event_id: EventId8;
  event_type: EventType7;
  home_id: HomeId9;
  occurred_at: OccurredAt7;
  payload: EnergyRefreshPayload;
  sequence: Sequence7;
  snapshot_required: SnapshotRequired7;
}
export interface DraftLockAcquiredEvent {
  change_domain: ChangeDomain8;
  event_id: EventId9;
  event_type: EventType8;
  home_id: HomeId10;
  occurred_at: OccurredAt8;
  payload: DraftLockAcquiredPayload;
  sequence: Sequence8;
  snapshot_required: SnapshotRequired8;
}
export interface DraftLockAcquiredPayload {
  lease_expires_at: LeaseExpiresAt;
  lease_id: LeaseId;
  terminal_id: TerminalId;
}
export interface PublishSucceededEvent {
  change_domain: ChangeDomain9;
  event_id: EventId10;
  event_type: EventType9;
  home_id: HomeId11;
  occurred_at: OccurredAt9;
  payload: PublishSucceededPayload;
  sequence: Sequence9;
  snapshot_required: SnapshotRequired9;
}
export interface PublishSucceededPayload {
  effective_at: EffectiveAt1;
  layout_version: LayoutVersion;
  published_by_terminal_id: PublishedByTerminalId;
}
export interface BackupRestoreCompletedEvent {
  change_domain: ChangeDomain10;
  event_id: EventId11;
  event_type: EventType10;
  home_id: HomeId12;
  occurred_at: OccurredAt10;
  payload: BackupRestoreCompletedPayload;
  sequence: Sequence10;
  snapshot_required: SnapshotRequired10;
}
export interface BackupRestoreCompletedPayload {
  backup_id: BackupId;
  effective_at: EffectiveAt2;
  layout_version: LayoutVersion1;
  restored_by_terminal_id: RestoredByTerminalId;
  settings_version: SettingsVersion1;
}
export interface VersionConflictDetectedEvent {
  change_domain: ChangeDomain11;
  event_id: EventId12;
  event_type: EventType11;
  home_id: HomeId13;
  occurred_at: OccurredAt11;
  payload: VersionConflictDetectedPayload;
  sequence: Sequence11;
  snapshot_required: SnapshotRequired11;
}
export interface VersionConflictDetectedPayload {
  last_event_id: LastEventId1;
  reason: Reason;
}
