import { spawnSync } from "node:child_process";
import { createRequire } from "node:module";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const require = createRequire(import.meta.url);
const scriptDir = dirname(fileURLToPath(import.meta.url));
const frontendDir = resolve(scriptDir, "..");
const backendDir = resolve(frontendDir, "..", "backend");
const exportOpenapiScript = resolve(backendDir, "scripts", "export_openapi.py");
const exportRealtimeSchemaScript = resolve(backendDir, "scripts", "export_realtime_schema.py");
const openapiPath = resolve(backendDir, "openapi.json");
const realtimeSchemaPath = resolve(backendDir, "realtime.schema.json");
const apiOutputPath = resolve(frontendDir, "src", "api", "types.generated.ts");
const realtimeOutputPath = resolve(frontendDir, "src", "ws", "realtime.generated.ts");
const openapiTypescriptPackageJson = require.resolve("openapi-typescript/package.json");
const openapiTypescriptCli = resolve(
  dirname(openapiTypescriptPackageJson),
  "bin",
  "cli.js",
);
const jsonSchemaToTypescriptPackageJson = require.resolve("json-schema-to-typescript/package.json");
const jsonSchemaToTypescriptCli = resolve(
  dirname(jsonSchemaToTypescriptPackageJson),
  "dist",
  "src",
  "cli.js",
);

function run(command, args) {
  const result = spawnSync(command, args, {
    cwd: frontendDir,
    stdio: "inherit",
  });

  if (result.status !== 0) {
    process.exit(result.status ?? 1);
  }
}

run("python", [exportOpenapiScript]);
run("python", [exportRealtimeSchemaScript]);
run(process.execPath, [openapiTypescriptCli, openapiPath, "-o", apiOutputPath]);
run(process.execPath, [
  jsonSchemaToTypescriptCli,
  realtimeSchemaPath,
  realtimeOutputPath,
  "--bannerComment",
  "/* This file was auto-generated by json-schema-to-typescript. Do not make direct changes. */",
]);

console.log(`generated: ${apiOutputPath}`);
console.log(`generated: ${realtimeOutputPath}`);
