import { spawnSync } from "node:child_process";
import { existsSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const require = createRequire(import.meta.url);
const scriptDir = dirname(fileURLToPath(import.meta.url));
const frontendDir = resolve(scriptDir, "..");
const backendDir = resolve(frontendDir, "..", "backend");
const backendVenvPython = resolve(backendDir, ".venv", "bin", "python");
const exportOpenapiScript = resolve(backendDir, "scripts", "export_openapi.py");
const exportRealtimeSchemaScript = resolve(backendDir, "scripts", "export_realtime_schema.py");
const openapiPath = resolve(backendDir, "openapi.json");
const realtimeSchemaPath = resolve(backendDir, "realtime.schema.json");
const apiOutputPath = resolve(frontendDir, "src", "api", "types.generated.ts");
const realtimeOutputPath = resolve(frontendDir, "src", "ws", "realtime.generated.ts");
const openapiTypescriptPackageJson = require.resolve("openapi-typescript/package.json");
const openapiTypescriptCli = resolve(
  dirname(openapiTypescriptPackageJson),
  "bin",
  "cli.js",
);
const jsonSchemaToTypescriptPackageJson = require.resolve("json-schema-to-typescript/package.json");
const jsonSchemaToTypescriptCli = resolve(
  dirname(jsonSchemaToTypescriptPackageJson),
  "dist",
  "src",
  "cli.js",
);

function commandExists(command) {
  const result = spawnSync(command, ["--version"], {
    stdio: "ignore",
  });
  return result.status === 0;
}

function resolvePythonCommand() {
  if (existsSync(backendVenvPython)) {
    return backendVenvPython;
  }
  const configured = process.env.PYTHON?.trim();
  if (configured) {
    return configured;
  }
  if (commandExists("python")) {
    return "python";
  }
  if (commandExists("python3")) {
    return "python3";
  }
  console.error("Python is required to export backend OpenAPI and realtime schemas.");
  process.exit(1);
}

function run(command, args) {
  const result = spawnSync(command, args, {
    cwd: frontendDir,
    stdio: "inherit",
  });

  if (result.status !== 0) {
    process.exit(result.status ?? 1);
  }
}

const pythonCommand = resolvePythonCommand();

run(pythonCommand, [exportOpenapiScript]);
run(pythonCommand, [exportRealtimeSchemaScript]);
run(process.execPath, [openapiTypescriptCli, openapiPath, "-o", apiOutputPath]);
run(process.execPath, [
  jsonSchemaToTypescriptCli,
  realtimeSchemaPath,
  realtimeOutputPath,
  "--bannerComment",
  "/* This file was auto-generated by json-schema-to-typescript. Do not make direct changes. */",
]);

console.log(`generated: ${apiOutputPath}`);
console.log(`generated: ${realtimeOutputPath}`);
