from __future__ import annotations

from src.app.containers.asset_backup_repositories_container import (
    get_backup_repository,
    get_backup_restore_repository,
    get_energy_account_repository,
    get_energy_snapshot_repository,
    get_page_asset_repository,
    get_unit_of_work,
)
from src.app.containers.auth_repositories_container import (
    get_auth_session_query_repository,
    get_home_auth_config_repository,
    get_pin_lock_repository,
    get_pin_session_repository,
    get_request_context_repository,
    get_terminal_bootstrap_token_repository,
    get_terminal_pairing_code_repository,
)
from src.app.containers.control_repositories_container import (
    get_device_control_query_repository,
    get_device_control_request_repository,
    get_device_control_transition_repository,
)
from src.app.containers.editor_repositories_container import (
    get_draft_hotspot_repository,
    get_draft_layout_repository,
    get_draft_lease_repository,
    get_editor_draft_query_repository,
    get_editor_lease_query_repository,
)
from src.app.containers.home_repositories_container import (
    get_device_catalog_command_repository,
    get_device_catalog_query_repository,
    get_device_control_schema_repository,
    get_device_repository,
    get_device_runtime_state_repository,
    get_home_overview_query_repository,
)
from src.app.containers.settings_repositories_container import (
    get_favorite_devices_repository,
    get_favorites_query_repository,
    get_function_settings_repository,
    get_layout_hotspot_repository,
    get_layout_version_repository,
    get_media_binding_repository,
    get_page_settings_repository,
    get_settings_snapshot_query_repository,
    get_settings_version_repository,
)
from src.app.containers.system_repositories_container import (
    get_ha_entity_sync_repository,
    get_ha_realtime_sync_repository,
    get_system_connection_repository,
    get_terminal_presence_repository,
    get_ws_event_outbox_repository,
)

__all__ = [
    "get_auth_session_query_repository",
    "get_backup_repository",
    "get_backup_restore_repository",
    "get_device_catalog_command_repository",
    "get_device_catalog_query_repository",
    "get_device_control_query_repository",
    "get_device_control_request_repository",
    "get_device_control_schema_repository",
    "get_device_control_transition_repository",
    "get_device_repository",
    "get_device_runtime_state_repository",
    "get_draft_hotspot_repository",
    "get_draft_layout_repository",
    "get_draft_lease_repository",
    "get_editor_draft_query_repository",
    "get_editor_lease_query_repository",
    "get_energy_account_repository",
    "get_energy_snapshot_repository",
    "get_favorite_devices_repository",
    "get_favorites_query_repository",
    "get_function_settings_repository",
    "get_ha_entity_sync_repository",
    "get_ha_realtime_sync_repository",
    "get_home_auth_config_repository",
    "get_home_overview_query_repository",
    "get_layout_hotspot_repository",
    "get_layout_version_repository",
    "get_media_binding_repository",
    "get_page_asset_repository",
    "get_page_settings_repository",
    "get_pin_lock_repository",
    "get_pin_session_repository",
    "get_request_context_repository",
    "get_settings_snapshot_query_repository",
    "get_settings_version_repository",
    "get_system_connection_repository",
    "get_terminal_bootstrap_token_repository",
    "get_terminal_pairing_code_repository",
    "get_terminal_presence_repository",
    "get_unit_of_work",
    "get_ws_event_outbox_repository",
]
