from __future__ import annotations

from src.app.containers import (
    auth_container,
    backup_container,
    catalog_container,
    core_container,
    editor_container,
    energy_container,
    realtime_container,
    repositories_container,
    settings_container,
)

get_settings = core_container.get_settings
get_database = core_container.get_database
get_clock = core_container.get_clock
get_event_id_generator = core_container.get_event_id_generator
get_id_generator = core_container.get_id_generator
get_version_token_generator = core_container.get_version_token_generator
get_capability_provider = core_container.get_capability_provider
get_weather_provider = core_container.get_weather_provider
get_connection_secret_cipher = core_container.get_connection_secret_cipher
get_home_assistant_bootstrap_provider = (
    core_container.get_home_assistant_bootstrap_provider
)
get_ha_control_gateway = core_container.get_ha_control_gateway
get_ha_connection_gateway = core_container.get_ha_connection_gateway
get_asset_storage = core_container.get_asset_storage

get_auth_session_query_repository = (
    repositories_container.get_auth_session_query_repository
)
get_request_context_repository = repositories_container.get_request_context_repository
get_home_auth_config_repository = repositories_container.get_home_auth_config_repository
get_pin_session_repository = repositories_container.get_pin_session_repository
get_terminal_bootstrap_token_repository = (
    repositories_container.get_terminal_bootstrap_token_repository
)
get_terminal_pairing_code_repository = (
    repositories_container.get_terminal_pairing_code_repository
)
get_pin_lock_repository = repositories_container.get_pin_lock_repository
get_home_overview_query_repository = (
    repositories_container.get_home_overview_query_repository
)
get_device_catalog_query_repository = (
    repositories_container.get_device_catalog_query_repository
)
get_settings_snapshot_query_repository = (
    repositories_container.get_settings_snapshot_query_repository
)
get_favorites_query_repository = repositories_container.get_favorites_query_repository
get_editor_draft_query_repository = (
    repositories_container.get_editor_draft_query_repository
)
get_editor_lease_query_repository = (
    repositories_container.get_editor_lease_query_repository
)
get_device_control_query_repository = (
    repositories_container.get_device_control_query_repository
)
get_device_repository = repositories_container.get_device_repository
get_device_catalog_command_repository = (
    repositories_container.get_device_catalog_command_repository
)
get_device_runtime_state_repository = (
    repositories_container.get_device_runtime_state_repository
)
get_device_control_schema_repository = (
    repositories_container.get_device_control_schema_repository
)
get_device_control_request_repository = (
    repositories_container.get_device_control_request_repository
)
get_device_control_transition_repository = (
    repositories_container.get_device_control_transition_repository
)
get_ws_event_outbox_repository = repositories_container.get_ws_event_outbox_repository
get_ha_realtime_sync_repository = repositories_container.get_ha_realtime_sync_repository
get_terminal_presence_repository = repositories_container.get_terminal_presence_repository
get_settings_version_repository = repositories_container.get_settings_version_repository
get_favorite_devices_repository = repositories_container.get_favorite_devices_repository
get_page_settings_repository = repositories_container.get_page_settings_repository
get_function_settings_repository = repositories_container.get_function_settings_repository
get_layout_version_repository = repositories_container.get_layout_version_repository
get_layout_hotspot_repository = repositories_container.get_layout_hotspot_repository
get_draft_layout_repository = repositories_container.get_draft_layout_repository
get_draft_hotspot_repository = repositories_container.get_draft_hotspot_repository
get_draft_lease_repository = repositories_container.get_draft_lease_repository
get_system_connection_repository = repositories_container.get_system_connection_repository
get_ha_entity_sync_repository = repositories_container.get_ha_entity_sync_repository
get_energy_account_repository = repositories_container.get_energy_account_repository
get_energy_snapshot_repository = repositories_container.get_energy_snapshot_repository
get_media_binding_repository = repositories_container.get_media_binding_repository
get_backup_repository = repositories_container.get_backup_repository
get_backup_restore_repository = repositories_container.get_backup_restore_repository
get_page_asset_repository = repositories_container.get_page_asset_repository
get_unit_of_work = repositories_container.get_unit_of_work

get_management_pin_guard = auth_container.get_management_pin_guard
get_access_token_resolver = auth_container.get_access_token_resolver
get_bootstrap_token_resolver = auth_container.get_bootstrap_token_resolver
get_request_context_service = auth_container.get_request_context_service
get_session_query_service = auth_container.get_session_query_service
get_pin_verification_service = auth_container.get_pin_verification_service
get_bootstrap_token_service = auth_container.get_bootstrap_token_service
get_terminal_pairing_code_service = auth_container.get_terminal_pairing_code_service

get_home_overview_query_service = catalog_container.get_home_overview_query_service
get_device_catalog_service = catalog_container.get_device_catalog_service

get_ha_entity_sync_service = realtime_container.get_ha_entity_sync_service
get_ha_realtime_sync_service = realtime_container.get_ha_realtime_sync_service
get_device_control_result_query_service = (
    realtime_container.get_device_control_result_query_service
)
get_realtime_service = realtime_container.get_realtime_service
get_device_control_command_service = realtime_container.get_device_control_command_service
get_system_connection_service = realtime_container.get_system_connection_service

get_settings_query_service = settings_container.get_settings_query_service
get_favorites_query_service = settings_container.get_favorites_query_service
get_sgcc_login_qr_code_service = settings_container.get_sgcc_login_qr_code_service
get_sgcc_container_restarter = settings_container.get_sgcc_container_restarter
get_settings_save_service = settings_container.get_settings_save_service

get_editor_session_service = editor_container.get_editor_session_service
get_editor_draft_service = editor_container.get_editor_draft_service
get_editor_publish_service = editor_container.get_editor_publish_service

get_energy_upstream_reader = energy_container.get_energy_upstream_reader
get_energy_binding_service = energy_container.get_energy_binding_service
get_energy_refresh_coordinator = energy_container.get_energy_refresh_coordinator
get_energy_service = energy_container.get_energy_service
get_energy_auto_refresh_service = energy_container.get_energy_auto_refresh_service

get_media_service = backup_container.get_media_service
get_floorplan_asset_service = backup_container.get_floorplan_asset_service
get_backup_service = backup_container.get_backup_service
get_backup_restore_service = backup_container.get_backup_restore_service
